{
  "version": 1,
  "status": "fail",
  "message": "\rLeap year divisible by 400 in leap year \u001b[1m\u001b[31m[E]\u001b[0m\u001b[0m                                                                                                          \n  Expected: <true>\n    Actual: <false>\n  \n  package:test_api                          expect\n  test/example_partial_fail_test.dart 40:7  main.<fn>.<fn>\n  \n\r\u001b[1m\u001b[1;30mloading test/example_partial_fail_test.dart\u001b[0m\u001b[0m                                                                                                                                               \nConsider enabling the flag chain-stack-traces to receive more detailed exceptions.\nFor example, 'dart test --chain-stack-traces'.\n\rLeap year divisible by 400 but not by 125 is still a leap year \u001b[1m\u001b[31m[E]\u001b[0m\u001b[0m                                                                                   \n  Expected: <true>\n    Actual: <false>\n  \n  package:test_api                          expect\n  test/example_partial_fail_test.dart 45:7  main.<fn>.<fn>\n  \n\r\u001b[1m\u001b[1;30mloading test/example_partial_fail_test.dart\u001b[0m\u001b[0m                                                                                                                                               \nConsider enabling the flag chain-stack-traces to receive more detailed exceptions.\nFor example, 'dart test --chain-stack-traces'.\n\r\u001b[31mSome tests failed.\u001b[0m                                                                                                                                                                        "
}
